#!/usr/bin/python

import socket

def get_remote_machine_info():
	remote_host = 'www.python.org'
	try:
		print socket.gethostbyname(remote_host)
	except socket.error, err_msg:
		print socket.error, err_msg

if __name__== '__main__':
	get_remote_machine_info()
